/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mathmath.start;

import java.awt.Color;
import java.util.Random;
import java.util.concurrent.TimeUnit;
import java.lang.Thread;
/**
 *
 * @author luisadominguez
 */
public class MathMath extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MathMath() {
        initComponents();
        // make the back panels hidden to begin with
        // it could be done inside 'private void initComponents below but
        // that block cannot be edited as it is self generated
        this.setLocationRelativeTo(null); // centers the frame on the screen
        level1.setVisible(false);
        level2.setVisible(false);
        level3.setVisible(false);
        level4.setVisible(false);
        certificate.setVisible(false);
        tryAgain.setVisible(false);
        level5.setVisible(false);
    }
    
    //variable declaration for stopwatch
    static int seconds = 0;
    static int minutes = 0;
    
    static boolean state = true;
    
    //creating random numbers to use in the game
    Random rand = new Random();
    
    //initialize the score
    public static int score = 0;
    
    //initialize bonus score for lives left
    public static int bonus = 0;
    
    //bonus setter
    public void setBonus(int bon) {
        bonus = bon;
        jLabel107.setText("" + bonus);
        
    }
    //score setter
    public void setScore(int s) {
        score = s;
        jLabel8.setText("" + score); //header
        jLabel68.setText("" + score); //certificate
        jLabel87.setText("" + score); //tryAgain page
    }
    
    //game score setter for certificate
    public void setGameScore(int p, int q) {
        //score = p;
        //bonus = q;
        int gameSc = p - q;
        jLabel106.setText("" + gameSc);
    }
    
    //initialize lives left
    static int lives = 4;
    static String heart = " Y Y Y Y ";
    
    //method to change heart numbers
    public void livesLeft(int l) {
        lives = l;
        if (l == 3) { heart = " Y Y Y "; }
        if (l == 2) { heart = " Y Y "; }
        if (l == 1) { heart = " Y "; }
        if (l == 0) { heart = "";}
        
        jLabel9.setText(heart);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    private void initialize() { //make back panels not visible
//        level1.setVisible(false);
//        level2.setVisible(false);
//        level3.setVisible(false);
//        level4.setVisible(false);
//        certificate.setVisible(false);
//    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBar = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        minute = new javax.swing.JLabel();
        second = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        start = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        nameError = new javax.swing.JLabel();
        level1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        err1 = new javax.swing.JLabel();
        level2 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        level3 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        level4 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jLabel103 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        certificate = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        tryAgain = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        help = new javax.swing.JPanel();
        level5 = new javax.swing.JPanel();
        jLabel96 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MathMath");
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideBar.setBackground(new java.awt.Color(41, 115, 115));
        sideBar.setPreferredSize(new java.awt.Dimension(200, 650));

        jButton1.setBackground(new java.awt.Color(24, 69, 69));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 133, 82));
        jButton1.setText("TURN OFF");
        jButton1.setToolTipText("Click this if you want to turn off the program.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(24, 69, 69));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 133, 82));
        jButton2.setText("HELP ME");
        jButton2.setToolTipText("Click this if you need any help with this program.");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mathmath/images/mathlogo4.png"))); // NOI18N

        jButton9.setBackground(new java.awt.Color(24, 69, 69));
        jButton9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(133, 255, 199));
        jButton9.setText("RESET");
        jButton9.setToolTipText("Click to set the time to 00:00");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("       TIMER");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        minute.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        minute.setForeground(new java.awt.Color(0, 249, 135));
        minute.setText("00:");
        minute.setToolTipText("Control this time with the three buttons below.");

        second.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        second.setForeground(new java.awt.Color(0, 249, 135));
        second.setText("00");
        second.setToolTipText("Control this time with the three buttons below.");

        jButton10.setBackground(new java.awt.Color(24, 69, 69));
        jButton10.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(133, 255, 199));
        jButton10.setText("START");
        jButton10.setToolTipText("Click ONLY ONCE to start the timer.");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(24, 69, 69));
        jButton11.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(133, 255, 199));
        jButton11.setText("STOP");
        jButton11.setToolTipText("Click this button to Stop the Timer");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel1)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(sideBarLayout.createSequentialGroup()
                            .addComponent(minute)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(second, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minute)
                    .addComponent(second))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(sideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        header.setBackground(new java.awt.Color(32, 92, 92));
        header.setPreferredSize(new java.awt.Dimension(800, 100));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PLAYER:");
        header.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LIVES LEFT:");
        header.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 114, -1));

        jLabel7.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 133, 82));
        jLabel7.setText("PLAYER NAME");
        jLabel7.setToolTipText("This should show your Name.");
        header.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 190, -1));

        jLabel5.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SCORE: ");
        header.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 70, -1));

        jLabel8.setFont(new java.awt.Font("Silom", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 133, 82));
        jLabel8.setText("0000");
        jLabel8.setToolTipText("This is your current score.");
        header.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 65, -1));

        jLabel9.setFont(new java.awt.Font("Webdings", 1, 32)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(234, 51, 116));
        jLabel9.setText(" Y Y Y Y");
        jLabel9.setToolTipText("This is how many times you can make mistakes.");
        header.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 240, 40));

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 800, -1));

        start.setBackground(new java.awt.Color(255, 255, 204));
        start.setPreferredSize(new java.awt.Dimension(800, 550));
        start.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 133, 82));
        jLabel3.setText("PLEASE ENTER YOUR FULL NAME");
        start.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        nameField.setBackground(new java.awt.Color(57, 57, 58));
        nameField.setFont(new java.awt.Font("Chalkduster", 2, 36)); // NOI18N
        nameField.setForeground(new java.awt.Color(255, 255, 255));
        nameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameField.setToolTipText("Click in this Chalkboard and type in your FULL Name. ");
        nameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 79, 42), 5, true));
        nameField.setCaretColor(new java.awt.Color(255, 133, 82));
        nameField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickName(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseDragName(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExitName(evt);
            }
        });
        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                keyTypedName(evt);
            }
        });
        start.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 499, 160));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 102));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mathmath/images/start-up.png"))); // NOI18N
        jButton3.setText("  -  START !  ");
        jButton3.setToolTipText("Click this button to start the game.");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn1MouseEnter(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn1MouseExit(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        start.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 409, 280, 98));

        nameError.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        nameError.setForeground(new java.awt.Color(204, 0, 255));
        start.add(nameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 499, 36));

        getContentPane().add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        level1.setBackground(new java.awt.Color(133, 255, 199));
        level1.setPreferredSize(new java.awt.Dimension(800, 550));
        level1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 102));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mathmath/images/start-up.png"))); // NOI18N
        jButton4.setText("  -  LEVEL 2 ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        level1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 416, 280, 98));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 102));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mathmath/images/charmander.png"))); // NOI18N
        jLabel10.setText("  LEVEL 1: ADDITION");
        level1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 342, 74));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(57, 57, 58));
        jLabel11.setText("10");
        level1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(115, 41, 41));
        jLabel12.setText("+");
        level1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(57, 57, 58));
        jLabel13.setText("20");
        level1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 44, -1));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(115, 41, 41));
        jLabel14.setText("=");
        level1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(57, 57, 58));
        jLabel16.setText("20");
        level1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(115, 41, 41));
        jLabel17.setText("+");
        level1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(115, 41, 41));
        jLabel19.setText("=");
        level1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, -1));

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(57, 57, 58));
        jLabel20.setText("50");
        level1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(115, 41, 41));
        jLabel22.setText("+");
        level1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 326, -1, -1));

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(57, 57, 58));
        jLabel23.setText("40");
        level1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 326, -1, -1));

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(115, 41, 41));
        jLabel24.setText("=");
        level1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(57, 57, 58));
        jLabel25.setText("70");
        level1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, -1));

        jTextField4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 133, 82));
        level1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 70, -1));

        jTextField5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 133, 82));
        level1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 70, -1));

        jTextField6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 133, 82));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                onlyNumbers(evt);
            }
        });
        level1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 70, -1));

        jLabel69.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 102, 51));
        level1.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 120, 30));

        jLabel70.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 102, 51));
        level1.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 120, 30));

        jLabel71.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 102, 51));
        level1.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 120, 30));

        jLabel108.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel108.setForeground(new java.awt.Color(255, 102, 0));
        level1.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 350, 40));

        err1.setForeground(new java.awt.Color(255, 51, 0));
        level1.add(err1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 100, 30));

        getContentPane().add(level1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        level2.setBackground(new java.awt.Color(204, 255, 204));
        level2.setPreferredSize(new java.awt.Dimension(800, 550));
        level2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 102));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mathmath/images/jigglypuff.png"))); // NOI18N
        jLabel26.setText("  LEVEL 2: SUBTRACTION");
        level2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 420, 74));

        jLabel27.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(57, 57, 58));
        jLabel27.setText("30");
        level2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 148, -1, -1));

        jLabel28.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(115, 41, 41));
        jLabel28.setText("-");
        level2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 148, -1, -1));

        jLabel29.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(57, 57, 58));
        jLabel29.setText("20");
        level2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 148, 44, -1));

        jLabel30.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(115, 41, 41));
        jLabel30.setText("=");
        level2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 148, -1, -1));

        jLabel32.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(57, 57, 58));
        jLabel32.setText("50");
        level2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 235, -1, -1));

        jLabel33.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(115, 41, 41));
        jLabel33.setText("-");
        level2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 235, -1, -1));

        jLabel35.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(115, 41, 41));
        jLabel35.setText("=");
        level2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 235, -1, -1));

        jLabel36.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(57, 57, 58));
        jLabel36.setText("10");
        level2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 235, -1, -1));

        jLabel38.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(115, 41, 41));
        jLabel38.setText("-");
        level2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 326, -1, -1));

        jLabel39.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(57, 57, 58));
        jLabel39.setText("40");
        level2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 326, -1, -1));

        jLabel40.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(115, 41, 41));
        jLabel40.setText("=");
        level2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        jLabel41.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(57, 57, 58));
        jLabel41.setText("30");
        level2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        jButton12.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 0, 102));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mathmath/images/start-up.png"))); // NOI18N
        jButton12.setText("  -  LEVEL 3  ");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        level2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 414, 280, 98));

        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 133, 82));
        level2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 70, -1));

        jTextField2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 133, 82));
        level2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 70, -1));

        jTextField3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 133, 82));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        level2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 60, -1));

        jLabel72.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 102, 51));
        level2.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 120, 30));

        jLabel73.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 102, 51));
        level2.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 120, 30));

        jLabel74.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 102, 51));
        level2.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 120, 30));

        jLabel112.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(255, 102, 0));
        level2.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 350, 40));

        getContentPane().add(level2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        level3.setBackground(new java.awt.Color(250, 217, 246));
        level3.setPreferredSize(new java.awt.Dimension(800, 550));
        level3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 102));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mathmath/images/pikachu.png"))); // NOI18N
        jLabel31.setText("  LEVEL 3: MULTIPLICATION");
        level3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 440, 74));

        jLabel34.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(57, 57, 58));
        jLabel34.setText("11");
        level3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 148, 40, -1));

        jLabel37.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(115, 41, 41));
        jLabel37.setText("X");
        level3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 148, -1, -1));

        jLabel42.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(57, 57, 58));
        jLabel42.setText("8");
        level3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 44, -1));

        jLabel43.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(115, 41, 41));
        jLabel43.setText("=");
        level3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 148, -1, -1));

        jLabel44.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(57, 57, 58));
        jLabel44.setText("12");
        level3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 235, 40, -1));

        jLabel45.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(115, 41, 41));
        jLabel45.setText("X");
        level3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 235, -1, -1));

        jLabel46.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(115, 41, 41));
        jLabel46.setText("=");
        level3.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 235, -1, -1));

        jLabel47.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(57, 57, 58));
        jLabel47.setText("84");
        level3.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 50, -1));

        jLabel48.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(115, 41, 41));
        jLabel48.setText("X");
        level3.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 326, -1, -1));

        jLabel49.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(57, 57, 58));
        jLabel49.setText("4");
        level3.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 324, 50, 40));

        jLabel50.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(115, 41, 41));
        jLabel50.setText("=");
        level3.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        jLabel51.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(57, 57, 58));
        jLabel51.setText("60");
        level3.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 40, -1));

        jTextField7.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 133, 82));
        level3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 80, -1));

        jTextField8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 133, 82));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        level3.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 80, -1));

        jTextField9.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 133, 82));
        level3.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 80, -1));

        jButton14.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 0, 102));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mathmath/images/start-up.png"))); // NOI18N
        jButton14.setText("  -  LEVEL 4  ");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        level3.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 280, 98));

        jLabel75.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 102, 51));
        level3.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 120, 30));

        jLabel76.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 102, 51));
        level3.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 120, 30));

        jLabel77.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(255, 102, 51));
        level3.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 120, 30));

        jLabel113.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel113.setForeground(new java.awt.Color(255, 102, 0));
        level3.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 350, 40));

        getContentPane().add(level3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        level4.setBackground(new java.awt.Color(181, 236, 251));
        level4.setPreferredSize(new java.awt.Dimension(800, 550));
        level4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 0, 102));
        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mathmath/images/snorlax.png"))); // NOI18N
        jLabel52.setText("  LEVEL 4: DIVISION");
        level4.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 350, 70));

        jLabel53.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(57, 57, 58));
        jLabel53.setText("11");
        level4.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 50, -1));

        jLabel54.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(115, 41, 41));
        jLabel54.setText("/");
        level4.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        jLabel55.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(57, 57, 58));
        jLabel55.setText("8");
        level4.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 44, -1));

        jLabel56.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(115, 41, 41));
        jLabel56.setText("=");
        level4.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        jLabel57.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(57, 57, 58));
        jLabel57.setText("12");
        level4.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 50, -1));

        jLabel58.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(115, 41, 41));
        jLabel58.setText("/");
        level4.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        jLabel59.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(115, 41, 41));
        jLabel59.setText("=");
        level4.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        jLabel60.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(57, 57, 58));
        jLabel60.setText("84");
        level4.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 40, -1));

        jLabel61.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(115, 41, 41));
        jLabel61.setText("/");
        level4.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        jLabel62.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(57, 57, 58));
        jLabel62.setText("4");
        level4.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 50, -1));

        jLabel63.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(115, 41, 41));
        jLabel63.setText("=");
        level4.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        jLabel64.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(57, 57, 58));
        jLabel64.setText("60");
        level4.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 50, -1));

        jTextField10.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 133, 82));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        level4.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 70, -1));

        jTextField11.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(255, 133, 82));
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        level4.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 70, -1));

        jTextField12.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(255, 133, 82));
        level4.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 70, -1));

        jButton13.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 0, 102));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mathmath/images/start-up.png"))); // NOI18N
        jButton13.setText("  -  DONE !  ");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        level4.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 280, 80));

        jLabel78.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 102, 51));
        level4.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 120, 30));

        jLabel79.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 102, 51));
        level4.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 120, 30));

        jLabel80.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 102, 51));
        level4.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 120, 30));

        jTextField15.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(255, 133, 82));
        level4.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 70, -1));

        jLabel97.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel97.setText("Quotient");
        level4.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 70, 30));

        jLabel98.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel98.setText("Remainder");
        level4.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 80, 30));

        jLabel99.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(102, 102, 102));
        jLabel99.setText("22");
        level4.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 50, -1));

        jLabel100.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel100.setForeground(new java.awt.Color(102, 102, 102));
        jLabel100.setText("/");
        level4.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jLabel101.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(102, 102, 102));
        jLabel101.setText("4");
        level4.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 44, -1));

        jLabel102.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(102, 102, 102));
        jLabel102.setText("=");
        level4.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        jTextField13.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(102, 102, 102));
        jTextField13.setText("5");
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        level4.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 70, -1));

        jTextField14.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(102, 102, 102));
        jTextField14.setText("2");
        level4.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 70, -1));

        jTextField16.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jTextField16.setForeground(new java.awt.Color(255, 133, 82));
        level4.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 70, -1));

        jTextField17.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jTextField17.setForeground(new java.awt.Color(255, 133, 82));
        level4.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 70, -1));

        jLabel103.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel103.setText("The first question has been solved for you as an example.");
        level4.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 450, -1));

        jLabel114.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel114.setForeground(new java.awt.Color(255, 102, 0));
        level4.add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 350, 40));

        getContentPane().add(level4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        certificate.setBackground(new java.awt.Color(157, 232, 251));
        certificate.setPreferredSize(new java.awt.Dimension(800, 550));
        certificate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 0, 102));
        jButton8.setText("  THANK YOU ! ");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        certificate.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 270, 50));

        jLabel15.setFont(new java.awt.Font("Luminari", 1, 36)); // NOI18N
        jLabel15.setText("Certificate");
        certificate.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mathmath/images/medal (1).png"))); // NOI18N
        certificate.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        jLabel21.setFont(new java.awt.Font("Snell Roundhand", 1, 24)); // NOI18N
        jLabel21.setText("Congratulations");
        certificate.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        jLabel65.setFont(new java.awt.Font("Snell Roundhand", 1, 26)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 133, 82));
        jLabel65.setText("Player Name");
        certificate.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        jLabel66.setFont(new java.awt.Font("Snell Roundhand", 1, 24)); // NOI18N
        jLabel66.setText("You have successfully completed the MathMath test. ");
        certificate.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jLabel67.setFont(new java.awt.Font("Snell Roundhand", 1, 24)); // NOI18N
        jLabel67.setText("Total Score : ");
        certificate.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));

        jLabel68.setFont(new java.awt.Font("Snell Roundhand", 1, 26)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 133, 82));
        jLabel68.setText("9000");
        certificate.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 70, -1));

        jLabel81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mathmath/images/falling-star.png"))); // NOI18N
        certificate.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        jLabel95.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mathmath/images/falling-star1.png"))); // NOI18N
        certificate.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton5.setBackground(new java.awt.Color(157, 232, 251));
        jButton5.setForeground(new java.awt.Color(255, 153, 51));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mathmath/images/curious.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        certificate.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 80, 70));

        jLabel104.setFont(new java.awt.Font("Snell Roundhand", 1, 24)); // NOI18N
        jLabel104.setText("Bonus from lives left : ");
        certificate.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        jLabel105.setFont(new java.awt.Font("Snell Roundhand", 1, 24)); // NOI18N
        jLabel105.setText("Game Score : ");
        certificate.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        jLabel106.setFont(new java.awt.Font("Snell Roundhand", 1, 24)); // NOI18N
        jLabel106.setForeground(new java.awt.Color(255, 133, 82));
        jLabel106.setText("9000");
        certificate.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 60, -1));

        jLabel107.setFont(new java.awt.Font("Snell Roundhand", 1, 24)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(255, 133, 82));
        jLabel107.setText("9000");
        certificate.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 70, -1));

        getContentPane().add(certificate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        tryAgain.setBackground(new java.awt.Color(157, 232, 251));
        tryAgain.setPreferredSize(new java.awt.Dimension(800, 550));
        tryAgain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton15.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 0, 102));
        jButton15.setText(" TRY AGAIN ! ");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        tryAgain.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 230, 60));

        jLabel82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mathmath/images/monster.png"))); // NOI18N
        tryAgain.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jLabel83.setFont(new java.awt.Font("Snell Roundhand", 1, 24)); // NOI18N
        jLabel83.setText("You have run out of :");
        tryAgain.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 220, -1));

        jLabel84.setFont(new java.awt.Font("Snell Roundhand", 1, 24)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(255, 133, 82));
        jLabel84.setText("Player Name");
        tryAgain.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 230, 40));

        jLabel85.setFont(new java.awt.Font("Snell Roundhand", 1, 24)); // NOI18N
        jLabel85.setText("You could not complete the MathMath test this time.");
        tryAgain.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        jLabel86.setFont(new java.awt.Font("Snell Roundhand", 1, 24)); // NOI18N
        jLabel86.setText("Your Score is: ");
        tryAgain.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, -1));

        jLabel87.setFont(new java.awt.Font("Snell Roundhand", 1, 24)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(255, 133, 82));
        jLabel87.setText("9000");
        tryAgain.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, -1, -1));

        jLabel88.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mathmath/images/bee.png"))); // NOI18N
        tryAgain.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, -1, -1));

        jLabel89.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mathmath/images/bee (1).png"))); // NOI18N
        tryAgain.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 30, 30));

        jLabel90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mathmath/images/bee (2).png"))); // NOI18N
        tryAgain.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 40, 40));

        jLabel91.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mathmath/images/bee (3).png"))); // NOI18N
        tryAgain.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, -1, -1));

        jLabel92.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mathmath/images/clouds (1).png"))); // NOI18N
        jLabel92.setToolTipText("");
        tryAgain.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel93.setFont(new java.awt.Font("Snell Roundhand", 1, 24)); // NOI18N
        jLabel93.setText("Sorry ");
        tryAgain.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, 40));

        jLabel94.setFont(new java.awt.Font("Webdings", 1, 24)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(232, 62, 122));
        jLabel94.setText(" Y Y");
        tryAgain.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, 20));

        getContentPane().add(tryAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        help.setBackground(new java.awt.Color(157, 232, 251));
        help.setPreferredSize(new java.awt.Dimension(800, 550));

        javax.swing.GroupLayout helpLayout = new javax.swing.GroupLayout(help);
        help.setLayout(helpLayout);
        helpLayout.setHorizontalGroup(
            helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        helpLayout.setVerticalGroup(
            helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        getContentPane().add(help, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        level5.setBackground(new java.awt.Color(255, 255, 204));
        level5.setPreferredSize(new java.awt.Dimension(800, 550));
        level5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel96.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(255, 0, 102));
        jLabel96.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mathmath/images/snorlax.png"))); // NOI18N
        jLabel96.setText("  LEVEL 5: FUN");
        level5.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 270, 74));

        jLabel109.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel109.setForeground(new java.awt.Color(255, 102, 51));
        level5.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 120, 30));

        jLabel110.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel110.setForeground(new java.awt.Color(255, 102, 51));
        level5.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 120, 30));

        jLabel111.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel111.setForeground(new java.awt.Color(255, 102, 51));
        level5.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 120, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        level5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 440, 410));

        getContentPane().add(level5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new HelpMe().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int namelength = nameField.getText().length();
        String name = nameField.getText();
        
        //use name where needed
        jLabel65.setText(name); //certificate page
        jLabel84.setText(name); //tryAgain page
        
        //String clickHere = "click here please !"; not used anymore
        if(namelength == 0){
          nameError.setText("Your name cannot be nothing, can it?");  
        } else {
            jLabel7.setText(name); //set player name on the header
            
            // set the random numbers for level 1 questions
            //question 1
            jLabel11.setText(String.valueOf(rand.nextInt(10)));
            jLabel13.setText(String.valueOf(rand.nextInt(10)));
            // Also can be written as : jLabel13.setText("" + rand1);
            //question 2
            jLabel16.setText("" + rand.nextInt(10));
            int rand1 = 10 + rand.nextInt(20); //to make the sum high enough
            jLabel20.setText("" + rand1);
            
            //question 3
            jLabel23.setText("" + rand.nextInt(20));
            int rand2 = 20 + rand.nextInt(20);
            jLabel25.setText("" + rand2); //to make the sum high enough
            
            start.setVisible(false);
            level1.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void mouseDragName(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseDragName
        // TODO add your handling code here:
        //nameField.setText("click here please !");
    }//GEN-LAST:event_mouseDragName

    private void mouseClickName(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickName
        // TODO add your handling code here:
//        nameField.setText("");
    }//GEN-LAST:event_mouseClickName

    private void mouseExitName(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExitName
        // TODO add your handling code here:
        // nameField.setText("");
    }//GEN-LAST:event_mouseExitName

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //check if empty
        int l1 = jTextField6.getText().length();
        int l2 = jTextField4.getText().length();
        int l3 = jTextField5.getText().length();
        if (l1 == 0 || l2 == 0 || l3 == 0) {
            jLabel108.setText("Please do not leave the boxes empty !");
        } else {
            //empty the warning text
            jLabel108.setText("");
            //check answers
            int a1 = Integer.parseInt(jLabel11.getText());
            int a2 = Integer.parseInt(jLabel13.getText());
            int sum1 = Integer.parseInt(jTextField6.getText());

            int a3 = Integer.parseInt(jLabel16.getText());
            int a4 = Integer.parseInt(jTextField4.getText());
            int sum2 = Integer.parseInt(jLabel20.getText());

            int a5 = Integer.parseInt(jTextField5.getText());
            int a6 = Integer.parseInt(jLabel23.getText());
            int sum3 = Integer.parseInt(jLabel25.getText());
        
            // check if you have lives left
            livesLeft(lives);
            if (lives > 0) {

                // if all correct
                if (a1 + a2 == sum1 && a3 + a4 == sum2 && a5 + a6 == sum3) {
                    //set score 100 per correct answer
                    score += 300;
                    setScore(score);
                    jLabel69.setText("CORRECT !");
                    jLabel70.setText("CORRECT !");
                    jLabel71.setText("CORRECT !");

                    //set the random numbers for next level (2)
                    //question 1
                    int rand3 = 10 + rand.nextInt(20);
                    jLabel27.setText(String.valueOf(rand3)); //to make the first number bigger
                    jLabel29.setText(String.valueOf(rand.nextInt(10)));

                    //question 2
                    int rand4 = 10 + rand.nextInt(20); //to make the sum high enough
                    jLabel32.setText("" + rand4);
                    jLabel36.setText("" + rand.nextInt(10));

                    //question 3
                    jLabel39.setText("" + rand.nextInt(20));
                    jLabel41.setText("" + rand.nextInt(20)); //to make the sum high enough

                    level1.setVisible(false);
                    level2.setVisible(true);
                } else {
                        //check answer 1
                        if (a1 + a2 != sum1) {
                            jLabel69.setText("Try Again");
                            lives -= 1;
                            livesLeft(lives);
                        } else { jLabel69.setText("CORRECT !"); }

                        //check answer 2
                        if (a3 + a4 != sum2) {
                            jLabel70.setText("Try Again");
                            lives -= 1;
                            livesLeft(lives);
                        } else { jLabel70.setText("CORRECT !"); }

                        //check answer 3
                        if (a5 + a6 != sum3) {
                            jLabel71.setText("Try Again");
                            lives -= 1;
                            livesLeft(lives);
                        } else { jLabel71.setText("CORRECT !"); }
                    }
            } else {
                level1.setVisible(false);
                tryAgain.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void keyTypedName(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyTypedName
        // TODO add your handling code here:
        
    }//GEN-LAST:event_keyTypedName

    private void btn1MouseEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseEnter
        // TODO add your handling code here:
        Color btnPanel1 = new Color(0xFF8552);
        jButton3.setBackground(btnPanel1);
    }//GEN-LAST:event_btn1MouseEnter

    private void btn1MouseExit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseExit
        // TODO add your handling code here:
        Color btnPanel1 = new Color(0xFFFFFF);
        jButton3.setBackground(btnPanel1);
    }//GEN-LAST:event_btn1MouseExit

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        state = false;
        
        seconds = 0;
        minutes = 0;
        
        second.setText("00");
        minute.setText("00:");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        state = true;
        
        Thread t = new Thread() {
            public void run() {
                for (;;) {
                    if (state == true) {
                        try {
                            sleep(1000);
                            if (seconds > 60) {
                                seconds = 0;
                                minutes++;
                            }
                            second.setText(""+seconds);
                            if (seconds < 10) {
                                second.setText("0" + seconds);
                            }
                            
                            seconds++;
                            minute.setText(minutes + ":");
                            if (minutes < 10) {
                                minute.setText("0" + minutes + ":");
                            }
                        } 
                        catch (Exception e) {
                            
                        }
                     } else {
                        break;
                    }
                }
            }
        };
        t.start();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        state = false;
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        //check if empty
        int l4 = jTextField2.getText().length();
        int l5 = jTextField3.getText().length();
        int l6 = jTextField1.getText().length();
        
        if (l4 == 0 || l5 == 0 || l6 == 0) {
            jLabel112.setText("Please do not leave the boxes empty !");
        } else {
            //empty the warning text
            jLabel108.setText("");
            //check answers
            int b1 = Integer.parseInt(jLabel27.getText());
            int b2 = Integer.parseInt(jLabel29.getText());
            int sub1 = Integer.parseInt(jTextField2.getText());

            int b3 = Integer.parseInt(jLabel32.getText());
            int b4 = Integer.parseInt(jTextField3.getText());
            int sub2 = Integer.parseInt(jLabel36.getText());

            int b5 = Integer.parseInt(jTextField1.getText());
            int b6 = Integer.parseInt(jLabel39.getText());
            int sub3 = Integer.parseInt(jLabel41.getText());
        
        
        
            // if you have lives left
            livesLeft(lives);
            if (lives > 0) {

                // if all correct
                if (b1 - b2 == sub1 && b3 - b4 == sub2 && b5 - b6 == sub3) {
                    //set score 100 per correct answer
                    score += 450;
                    setScore(score);
                    jLabel72.setText("CORRECT !");
                    jLabel73.setText("CORRECT !");
                    jLabel74.setText("CORRECT !");

                    //set the random numbers for next level questions
                    //question 1
                    jLabel34.setText("" + rand.nextInt(10));
                    jLabel42.setText("" + rand.nextInt(10));

                    //question 2
                    jLabel44.setText("" + rand.nextInt(15));
                    jLabel47.setText("" + rand.nextInt(10));

                    //question 3
                    jLabel49.setText("" + rand.nextInt(15));
                    jLabel51.setText("" + rand.nextInt(15));

                    //Finally close current panel and open new level 
                    level2.setVisible(false);
                    level3.setVisible(true);
                } else {
                        //check answer 1
                        if (b1 - b2 != sub1) {
                            jLabel72.setText("Try Again");
                            lives -= 1;
                            livesLeft(lives);
                        } else { jLabel72.setText("CORRECT !"); }

                        //check answer 2
                        if (b3 - b4 != sub2) {
                            jLabel73.setText("Try Again");
                            lives -= 1;
                            livesLeft(lives);
                        } else { jLabel73.setText("CORRECT !"); }

                        //check answer 3
                        if (b5 - b6 != sub3) {
                            jLabel74.setText("Try Again");
                            lives -= 1;
                            livesLeft(lives);
                        } else { jLabel74.setText("CORRECT !"); }
                    }
            } else {
                level2.setVisible(false);
                tryAgain.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        //check if empty
        int l7 = jTextField8.getText().length();
        int l8 = jTextField9.getText().length();
        int l9 = jTextField7.getText().length();
        if (l7 == 0 || l8 == 0 || l9 == 0) {
            jLabel113.setText("Please do not leave the boxes empty !");
        } else {
            //empty the warning text
            jLabel113.setText("");
            int c1 = Integer.parseInt(jLabel34.getText());
            int c2 = Integer.parseInt(jLabel42.getText());
            int product1 = Integer.parseInt(jTextField8.getText());

            int c3 = Integer.parseInt(jLabel44.getText());
            int c4 = Integer.parseInt(jLabel47.getText());
            int product2 = Integer.parseInt(jTextField9.getText());

            int c5 = Integer.parseInt(jLabel49.getText());
            int c6 = Integer.parseInt(jLabel51.getText());
            int product3 = Integer.parseInt(jTextField7.getText());

            // if you have lives left
            livesLeft(lives);
            if (lives > 0) {

                // if all correct
                if (c1 * c2 == product1 && c3 * c4 == product2 && c5 * c6 == product3) {
                    //set score 100 per correct answer
                    score += 600;
                    setScore(score);
                    jLabel75.setText("CORRECT !");
                    jLabel76.setText("CORRECT !");
                    jLabel77.setText("CORRECT !");

                    //setting up the random numbers for next level
                    //question 1
                    int rand5 = 20 + rand.nextInt(20); // to make the divident high enough
                    jLabel53.setText("" + rand5);
                    int rand6 = 1 + rand.nextInt(10); // to avoid zero as a divisor
                    jLabel55.setText("" + rand6);

                    //question 2
                    int rand7 = 30 + rand.nextInt(30);
                    jLabel57.setText("" + rand7);
                    int rand8 = 2 + rand.nextInt(11); // to avoid zero and 1 as a divisor
                    jLabel60.setText("" + rand8);

                    //question 3
                    int rand9 = 40 + rand.nextInt(40);
                    jLabel62.setText("" + rand9);
                    int rand10 = 5 + rand.nextInt(11);
                    jLabel64.setText("" + rand10);

                    level3.setVisible(false);
                    level4.setVisible(true);
                } else {
                        //check answer 1
                        if (c1 * c2 != product1) {
                            jLabel75.setText("Try Again");
                            jTextField2.setText("");
                            lives -= 1;
                            livesLeft(lives);
                        } else { jLabel75.setText("CORRECT !"); }

                        //check answer 2
                        if (c3 * c4 != product2) {
                            jLabel76.setText("Try Again");
                            jTextField3.setText("");
                            lives -= 1;
                            livesLeft(lives);
                        } else { jLabel76.setText("CORRECT !"); }

                        //check answer 3
                        if (c5 * c6 != product3) {
                            jLabel77.setText("Try Again");
                            jTextField1.setText("");
                            lives -= 1;
                            livesLeft(lives);
                        } else { jLabel77.setText("CORRECT !"); }
                    }
            } else {
                level3.setVisible(false);
                tryAgain.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        //check if empty
        int l10 = jTextField10.getText().length();
        int l11 = jTextField11.getText().length();
        int l12 = jTextField12.getText().length();
        if (l10 == 0 || l11 == 0 || l12 == 0) {
            jLabel114.setText("Please do not leave the boxes empty !");
        } else {
            //empty the warning text
            jLabel114.setText("");
            int d1 = Integer.parseInt(jLabel53.getText());
            int d2 = Integer.parseInt(jLabel55.getText());
            int d3 = Integer.parseInt(jLabel57.getText());
            int d4 = Integer.parseInt(jLabel60.getText());
            int d5 = Integer.parseInt(jLabel62.getText());
            int d6 = Integer.parseInt(jLabel64.getText());

            int div1 = Integer.parseInt(jTextField10.getText());
            int div2 = Integer.parseInt(jTextField11.getText());
            int div3 = Integer.parseInt(jTextField12.getText());

            int rem1 = Integer.parseInt(jTextField15.getText());
            int rem2 = Integer.parseInt(jTextField16.getText());
            int rem3 = Integer.parseInt(jTextField17.getText());

            // Check if you have any lives left
            livesLeft(lives);
            if (lives > 0) {

               // Check if all correct
                    if (d1 / d2 == div1 && d3 / d4 == div2 && d5 / d6 == div3 &&
                            d1 % d2 == rem1 && d3 % d4 == rem2 && d5 % d6 == rem3) {

                            // score 250 per correct answer
                            int level4Score = 750;

                            //bonus score for lives left
                            bonus = lives * 100;
                            setBonus(bonus);

                            // set total score for the game
                            score += bonus + level4Score;
                            setScore(score);

                            //set game score
                            setGameScore(score, bonus);

                            // display "Correct"
                            jLabel78.setText("CORRECT !");
                            jLabel79.setText("CORRECT !");
                            jLabel80.setText("CORRECT !");
                            // hide current level and show next panel
                            level4.setVisible(false);
                            certificate.setVisible(true);

                    } else {
                            // Check answer 1
                            if (d1 / d2 != div1 || d1 % d2 != rem1) {
                                    jLabel78.setText("Try Again");
                                    lives -= 1;
                                    livesLeft(lives);
                            } else { jLabel78.setText("CORRECT !"); } 

                            // Check answer 2
                            if (d3 / d4 != div2 || d3 % d4 != rem2) {
                                    jLabel79.setText("Try Again");
                                    lives -= 1;
                                    livesLeft(lives);
                            } else { jLabel79.setText("CORRECT !"); }

                            // Check answer 3
                            if (d5 / d6 != div3 || d5 % d6 != rem3) {
                                    jLabel80.setText("Try Again");
                                    lives -= 1;
                                    livesLeft(lives);
                            } else { jLabel80.setText("CORRECT !"); }
                    }

            } else {
                    level4.setVisible(false);
                    tryAgain.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        score = 0;
        setScore(score);
        lives = 4;
        heart = " Y Y Y Y ";
        livesLeft(lives);
        tryAgain.setVisible(false);
        level1.setVisible(true);
        
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        certificate.setVisible(false);
        level5.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void onlyNumbers(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_onlyNumbers
        // TODO add your handling code here:
        try {
            int i = Integer.parseInt(jTextField6.getText());
            err1.setText("");
        } catch (NumberFormatException e1) {
            err1.setText("Numbers Only!");
        }
    }//GEN-LAST:event_onlyNumbers

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathMath().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel certificate;
    private javax.swing.JLabel err1;
    private javax.swing.JPanel header;
    private javax.swing.JPanel help;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel level1;
    private javax.swing.JPanel level2;
    private javax.swing.JPanel level3;
    private javax.swing.JPanel level4;
    private javax.swing.JPanel level5;
    private javax.swing.JLabel minute;
    private javax.swing.JLabel nameError;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel second;
    private javax.swing.JPanel sideBar;
    private javax.swing.JPanel start;
    private javax.swing.JPanel tryAgain;
    // End of variables declaration//GEN-END:variables
}
